use lazy_static::lazy_static;
use crate::bin::*;
use crate::field;

lazy_static!{
    pub static ref ITEMS: Vec<Field> = vec![
        field!("flippy_file",               str, 32,        0x00),
        field!("inv_file",                  str, 32,        0x20),
        field!("unique_inv_file",           str, 32,        0x40),
        field!("set_inv_file",              str, 32,        0x60),
        field!("code",                      ItemCode,       0x80),
        field!("norm_code",                 ItemCode,       0x84),
        field!("uber_code",                 ItemCode,       0x88),
        field!("ultra_code",                ItemCode,       0x8C),
        field!("alternate_gfx",             ItemCode,       0x90),
        field!("pspell",                    u32,            0x94),
        field!("state",                     u16,            0x98),
        field!("curse_state",               u16[2],         0x9A),
        field!("stat",                      u16[3],         0x9E),
        field!("calc",                      u32[3],         0xA4),
        field!("len",                       u32,            0xB0),
        field!("spell_desc",                u8,             0xB4),
        field!("__pad_B5",                  u8,             0xB5),
        field!("spell_desc_str",            u16,            0xB6),
        field!("spell_desc_calc",           u32,            0xB8),
        field!("better_gem",                u32,            0xBC),
        field!("weap_class",                u32,            0xC0),
        field!("weap_class_2_hand",         u32,            0xC4),
        field!("transmogrify_type",         u32,            0xC8),
        field!("min_ac",                    i32,            0xCC),
        field!("max_ac",                    i32,            0xD0),
        field!("gamble_cost",               u32,            0xD4),
        field!("speed",                     i32,            0xD8),
        field!("bit_field_1",               u32,            0xDC),
        field!("cost",                      u32,            0xE0),
        field!("min_stack",                 u32,            0xE4),
        field!("max_stack",                 u32,            0xE8),
        field!("spawn_stack",               u32,            0xEC),
        field!("gem_offset",                u32,            0xF0),
        field!("name_str",                  StringId,       0xF4),
        field!("version",                   u16,            0xF6),
        field!("auto_prefix",               u16,            0xF8),
        field!("missile_type",              u16,            0xFA),
        field!("rarity",                    u8,             0xFC),
        field!("level",                     u8,             0xFD),
        field!("min_dam",                   u8,             0xFE),
        field!("max_dam",                   u8,             0xFF),
        field!("min_mis_dam",               u8,             0x100),
        field!("max_mis_dam",               u8,             0x101),
        field!("2_hand_min_dam",            u8,             0x102),
        field!("2_hand_max_dam",            u8,             0x103),
        field!("range_adder",               u8,             0x104),
        field!("unk_105",                   u8,             0x105),
        field!("str_bonus",                 i16,            0x106),
        field!("dex_bonus",                 i16,            0x108),
        field!("req_str",                   u16,            0x10A),
        field!("req_dex",                   u16,            0x10C),
        field!("absorb",                    u8,             0x10E),
        field!("inv_width",                 u8,             0x10F),
        field!("inv_height",                u8,             0x110),
        field!("block",                     u8,             0x111),
        field!("durability",                u8,             0x112),
        field!("no_durability",             u8,             0x113),
        field!("missile",                   u8,             0x114),
        field!("component",                 u8,             0x115),
        field!("armor_comp",                u8[6],          0x116),
        field!("2_handed",                  u8,             0x11C),
        field!("useable",                   u8,             0x11D),
        field!("type",                      i16[2],         0x11E),
        field!("sub_type",                  u8,             0x122),
        field!("unk_123",                   u8,             0x123),
        field!("drop_sound",                u16,            0x124),
        field!("use_sound",                 u16,            0x126),
        field!("drop_sfx_frame",            u8,             0x128),
        field!("unique",                    u8,             0x129),
        field!("quest",                     u8,             0x12A),
        field!("quest_diff_check",          u8,             0x12B),
        field!("transparent",               u8,             0x12C),
        field!("trans_tbl",                 u8,             0x12D),
        field!("__pad_12E",                 u8,             0x12E),
        field!("light_radius",              u8,             0x12F),
        field!("belt",                      u8,             0x130),
        field!("auto_belt",                 u8,             0x131),
        field!("stackable",                 u8,             0x132),
        field!("spawnable",                 u8,             0x133),
        field!("spell_icon",                u8,             0x134),
        field!("dur_warning",               u8,             0x135),
        field!("quantity_warning",          u8,             0x136),
        field!("has_inv",                   u8,             0x137),
        field!("gem_sockets",               u8,             0x138),
        field!("transmogrify",              u8,             0x139),
        field!("tmog_min",                  u8,             0x13A),
        field!("tmog_max",                  u8,             0x13B),
        field!("hit_class",                 u8,             0x13C),
        field!("1_or_2_handed",             u8,             0x13D),
        field!("gem_apply_type",            u8,             0x13E),
        field!("level_req",                 u8,             0x13F),
        field!("magic_level",               u8,             0x140),
        field!("transform",                 i8,             0x141),
        field!("inv_trans",                 i8,             0x142),
        field!("compact_save",              u8,             0x143),
        field!("skip_name",                 u8,             0x144),
        field!("nameable",                  u8,             0x145),
        field!("vendor_min",                u8[17],         0x146),
        field!("vendor_max",                u8[17],         0x157),
        field!("vendor_magic_min",          u8[17],         0x168),
        field!("vendor_magic_max",          u8[17],         0x179),
        field!("vendor_magic_lvl",          u8[17],         0x18A),
        field!("__pad_19B",                 u8,             0x19B),
        field!("nightmare_upgrade",         u32,            0x19C),
        field!("hell_upgrade",              u32,            0x1A0),
        field!("perm_store_item",           u8,             0x1A4),
        field!("multibuy",                  u8,             0x1A5),
        field!("__pad_1A6",                 u16,            0x1A6),
    ];
}
